version: '2.1'
services:
  wordpress:
   image: wordpress
   restart: always
   ports:
     - '8080:80'
   depends_on:
     db:
      condition: service_started
   links:
     - db
   volumes:
      - ./www:/var/www/html

  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   restart: always
   ports:
     - '8081:80'
   environment:
     - PMA_HOST=db
   depends_on:
     db:
      condition: service_started
   links:
     - db
  db:
    image: mysql
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

